just-install/registry

just-install.json

Bulk Crap Uninstaller is an uninstall program where you can uninstall multiple programs at a time. This program features some nice features such as killing the program before you install it, removing traces after an uninstall and more.
I've tested it and it downloaded and installed successfully in silent mode.

Added BCUninstaller (Bulk Crap Uninstaller)

---

just-install.json

even if visual-studio-code is using innosetup, it automatically starts after the installation. i changed the config according to https://stackoverflow.com/questions/42582230/how-to-install-visual-studio-code-silently-without-auto-open-when-installation while still using the standard innosetup flags.

fix(config): make visual-studio-code actually silent

---

just-install.json

abandoned: replaced by python27-pillow:
https://pillow.readthedocs.io/en/latest/index.html
(im going to create a pull request for python27-pillow and multiple other additions as soon as the removals are merged)

feat(config): remove python27-pil

---

just-install.json

From https://github.com/pfn/keepasshttp:
> KeePassHttp is a plugin for KeePass 2.x and provides a secure means of exposing KeePass entries via HTTP for clients to consume.

Added KeePassHttp plugin

---

just-install.json

switch from ActivePerl to StrawberryPerl, since ActivePerl [dont provice 32bit-executables](https://www.activestate.com/activeperl/downloads) for the latest perl versions.
StrawberryPerl also automatically sets the shims.

feat(config): update perl

---

just-install.json

starting from [pyqt 4.11.4](https://sourceforge.net/projects/pyqt/files/PyQt4/PyQt-4.11.4/) and [pyqt 5.6](https://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.6/), pyqt isnt available as executables anymore, and [the installation via pip is recommended](http://pyqt.sourceforge.net/Docs/PyQt5/installation.html).

feat(config): remove pyqt

---

just-install.json

Updated:
- dotnet (4.7.2)
New:
- nettime (3.14)
- physx (9.16.0318)
- redist-2005 (8.0.61000)
- redist-2008 (9.0.30729.6161)
- redist-2010 (10.0.40219.325)
- redist-2012 (11.0.61030)
- redist-2013 (12.0.40664.0)
- redist-2015 (14.0.24215.0)
- redist-2017 (14.14.26429.4)

updated dotnet, added nettime,physx and Visual C++ Redistributables

---

just-install.json

Instead of the standard-exe, this commit contains a link to the "enterprise"-installer (MSI-Format and it doesnt have toolbars and such). The software itself should be identical to the version provided by the standard-exe (at least i didnt found anything hinting otherwise).
I created a PR to make sure its OK for you (@lvillani @guiweber @geek1011).

add foxitreader

---

just-install.json

They silently install Google Chrome, which is user hostile.
References #109

Remove Defraggler and Recuva from Piriform

---

just-install.json

Apparently the foobar2000 website generates temporary download links. Whoops. I had to mirror the installer to make this package usable.

Fix foobar2000

---

just-install.json

Command line video/audio format conversion utility. This is also used internally by youtube-dl (which is already packaged) to support downloads from some websites.

Add ffmpeg

---

just-install.json

I found out that they have a symlink to the "latest" version on their server, conveniently labelled just that. What do you know, it's nowhere on the actual website. The jiup-go rule mentioned in #123 should no longer be needed after this.

Fix mednafen version

---

just-install.json

Code::Blocks is one of the programs required for the final exams in Poland: https://cke.gov.pl/images/_KOMUNIKATY/20180820%20EM%20Komunikat%20o%20egzaminie%20z%20informatyki.pdf
It is very important for us (as a school) to have is in just-install.

Add Code::Blocks 17.12

---

just-install.json

The dbeaver installer appears to have changed. It no longer likes the `/NCRC` flag that's part of the NSIS installer args.
This PR uses custom arguments to run dbeaver installer.
```
PS C:\Windows\system32> just-install dbeaver
2019/10/04 09:24:33 Updating registry from: https://just-install.github.io/registry/just-install-v4.json
79.91 KiB / ? [-------------------------------------=------------------------------------------------] 15.64 MiB/s 0s
2019/10/04 09:24:33 x86_64 - https://github.com/dbeaver/dbeaver/releases/download/6.2.1/dbeaver-ce-6.2.1-x86_64-setup.exe
48.58 MiB / 48.58 MiB [=======================================================================] 100.00% 24.36 MiB/s 1s
2019/10/04 09:24:35 Running C:\Users\Nithin\AppData\Local\Temp\just-install\B40E6373.exe /S /NCRC …
```

Use custom arguments for dbeaver installer

---

just-install.json

Per https://blenderartists.org/t/32-bit-programming-is-finally-dead-blender-2-81-dev-now-64-bit-only/1172927

Update blender to 2.81 (drop 32bit support)

---

just-install.json

Minimal install of Python3. No tk and no IDLE. Ideal for an environment where you just need to run your Python3 scripts.

Add python3-minimal

---

just-install-v4.json

Doesn't have a stable download URL
I wanted to make an updater rule when I realized that `313` the the artifact name is the build id. Next build artifact will have a different id in the name and the link will stop working. We can't point to artifacts of a build because everyday there is a new build and they only keep last 10 builds so the link would work for 10 days.
I'm sorry for that. I should have checked that when adding the rule. I will open an issue at KDE and hope that they can provide stable download URLs.

Remove okular

---

just-install-v4.json

The installer requires either /allusers or /currentusers flag to be
present

Fix bleachbit installer

---

just-install-v4.json

Triple listed on https://windirstat.net/download.html#mirrors is another option, but I think that SF is less likely to go sown.

Change windirstat download mirror

---

just-install-v4.json

Contains the following version changes for AdoptOpenJDK:
- 13.0.1+9 → 13.0.2+8
- 14.0.1+7.1 → 14.0.2+12
- New: 15.0.1+9

Add AdoptOpenJDK 15 and update previous releases

---

just-install-v4.json

If the `ALLUSERS` option is provided to the `.msi` executor, the Python 2 setup fails with exit code `1603`. Removing the `ALLUSERS` option fixes it.

Fix Python 2 installation

---

just-install-v4.json

Reverts just-install/registry#237
The issue only occurs when the Microsoft Visual C++ 2008 redistributable is missing on the system prior to running the Python 2 setup (e.g. on a Windows Sandbox).
This is not something j-i can handle (at least for now) and should be resolved by explicitly installing Visual C++ beforehand.

Revert "Fix Python 2 installation"

---

just-install-v4.json

The authors of `doublecmd` also provide an `.exe` installer. Using it instead of the `.msi` fixes the 32-bit installation.

Fix Double Commander x86 setup

---

just-install-v4.json
just-install-v4.schema.json

Also remove the "jetbrains-nsis" installer from the JSON schema since it
should not be required anymore (and will be removed from a future
just-install release).

Update Jetbrains IDEs to 2020.3 and switch to standard "nsis" installer

---

just-install-v4.json

solve #250. Ubisoft has recently phased out Uplay in favor of thier new Ubisoft Connect. This needs to be updated in the registry, which currently still has the old uplay.

Update uplay -> ubisoft connect
