just-install.json

Added Webtorrent

---

just-install.json

Added
- [GOG Galaxy](https://www.gog.com/galaxy)
- [Telegram Desktop](https://desktop.telegram.org/)
- [Audacity](http://www.audacityteam.org/)
also updated Calibre, so the tests aren't failing anymore.

Package additions + Build fix

---

docs/registry.md

- Fixed grammar errors
- Updated links
- Added link to registry

Link and grammar fixes

---

README.md

Updated the link to just-install-updater

Updated just-install link

---

just-install.json

I have added one of my apps: [SimpleMarkdown](http://geek1011.github.io/SimpleMarkdown/).

Added simplemarkdown

---

just-install.json

Updated Notepad++ version and added the 64 bit link.

Registry with updated Notepad++

---

just-install.json

Should use "latest" because of no version specific download

---

just-install.json

Add [Firefox ESR](https://www.mozilla.org/en-US/firefox/organizations/).

Add Firefox ESR

---

just-install.json

Changed the file names and version number to the latest stable Everything multilingual release.

Updated Everything to 1.4.1.877

---

just-install.json

feat(config): add simplenote
feat(config): add visual-studio-code x86_64
fix(config): fix go x86_64
feat(config): add anydesk

add and fix couple of stuff

---

just-install.json

feat(config): add cdburnerxp;
feat(config): add openvpn;
feat(config) add naps2;
feat(config) add vivaldi;
feat(config) add winrar

add couple of more stuff

---

just-install.json

Since atom  and other software are using the [squirrel-installer](https://github.com/Squirrel/Squirrel.Windows), you can use the `--silent` flag to install software quietly.
i edited the configs for atom, slack, discord and webtorrent.
i also added new software (brave, rambox, onlyoffice-desktopeditors).
Sorry for not making pull-requests for single commits. i would need to create new branches and rebase the commits, and i am an **absolute** noob in git and programming in general :( please forgive me.
i only started a couple of days ago learning git and golang as my first programming language.
also, i want to contribute to the just-install-updater too, but i cant bring the RegEx to work. 
for help, i would be grateful.

add silent flags and new software

---

just-install.json

added gitkraken after @geek1011 mentioned it in #31

feat(config): add gitkraken

---

just-install.json

i played with virtualbox a bit, because it didnt install quietly. and i found this:
so i edited the registry accordingly.

fix(config): make virtualbox installation silent

---

just-install.json

Details for the installer can be obtained @ https://workflowy.com/downloads/windows/

added workflowy to registry

---

just-install.json

From https://sourceforge.net/projects/ditto-cp/:
> Ditto is an extension to the standard windows clipboard. It saves each item placed on the clipboard allowing you access to any of those items at a later time. Ditto allows you to specify what gets saved, text, images or html.

Added Ditto

---

just-install.json

simplemarkdown isnt available anymore: https://github.com/geek1011/SimpleMarkdown/

feat(config): remove simplemarkdown

---

just-install.json

feat(config): add etcher

---

just-install.json

abandoned:
https://www.python.org/download/releases/2.6.6/

feat(config): remove python26

---

just-install.json

abandoned: 
https://support.plex.tv/articles/208175907-how-are-plex-media-player-and-plex-home-theater-different/

feat(config): remove plex-home-theater

---

just-install.json

outdated: replaced by visualstudio-community-2017
(im going to create a pull request for visualstudio-community-2017 and multiple other additions as soon as the removals are merged)

feat(config): remove visualstudio-express-desktop

---

just-install.json

what the hell did my git just do D:

feat(config): add keypassxc

---

just-install.json

feat(config): update python2 entries

---

just-install.json

#71 
like this or with "latest" as version?

feat(config): add visual-studio-community

---

just-install.json

From https://www.stardock.com/products/fences/:
> Automatically organize your desktop shortcuts and icons with Fences
Unfortunately, similar to `battlenet`, the installation hangs during the activation step.

Added Stardock Fences

---

just-install.json

Added Citrix Receiver + Open Hardware Monitor

Added Citrix Receiver + Open Hardware Monitor

---

just-install.json

Hi, this is my first PR to this awesome project and I am not sure if my changes are 100% correct.
So it would be great if you could have a look. Thank you so much! 😘

Add Mp3tag, Postman & Mountain Duck

---

just-install.json

From https://bitbucket.org/efotinis/deskpins:
> ... a Windows program that can make any application window top-most.

Added DeskPins

---

just-install.json

Add retroarch, update youtube-dl entry

Add and update

---

just-install.json

I'll have another look over the updater script when I have some free time, I've added a few applications now and I'm not wanting them getting behind on versions.

Add additional applications

---

just-install.json

I added Lightshot entry with latest update, already tested and works like a charm.

Added Lightshot

---

just-install.json

Update rufus version

---

just-install.json

update redist-2017 version

---

just-install.json

A multi-system retro console emulator

Add mednafen

---

just-install.json

A program to map gamepad inputs to keyboard keys or mouse buttons/movements.

Add AntiMicro

---

just-install.json

Peer-to-peer file/folder synchronization and sharing tool.

Add Resilio Sync

---

just-install.json

Add paint.net

---

just-install.json

Add itch.io app

---

just-install.json

Game streaming client for use with Nvidia Geforce Experience.

Add Moonlight

---

just-install.json

A file encryption program. Comes in two flavours -- a GUI version with Explorer right-click integration (packaged here as `aescrypt-gui`) and a command line version (packaged here as `aescrypt-cli`).

Add AESCrypt

---

just-install.json

This pull request updates Go from 1.12.7 to 1.12.9.

Update Go to 1.12.9

---

just-install.json

Unicode is the only version proposed since Inno Setup 6.

Fix inno setup url

---

just-install.json

Switch to the latest available version.

Use latest workflowy version

---

just-install.json

Add AxCrypt

---

just-install-v4.json

Very useful when deploying QEMU/KVM VMs with Windows.

Add spice-guest-tools

---

just-install-v4.json

Requires /allusers switch which my just-install doesn't supply but works
fine

Add rclone-browser

---

just-install-v4.json

I think that it would be nice to wait for them to fix http://forums.codeblocks.org/index.php/topic,23747.new.html.

Update Code::Blocks to 20.03

---

just-install-v4.json

A small step to get passing CI.

Change Sumatra PDF download URL

---

just-install-v4.json

CI has been failing for months.

Remove EitherMouse and Mullvad

---

just-install-v4.json

Add Okular

---

just-install-v4.json

Bitbucket repository was deleted

Remove deskpins

---

just-install-v4.json

fix for https://github.com/just-install/registry/issues/199

Adjust sumatrapdf entry

---

just-install-v4.json

The old one is returning a HTML page

Change opera download url

---

just-install-v4.json

New Task and Time Management application. More on [empoche.com](https://empoche.com)

Add Empoche 0.3.0

---

just-install-v4.json

Add Timecamp

---

just-install-v4.json

I might fix it one day, but for now let's remove it.

Remove ffmpeg

---

just-install-v4.json

Fix for jetbrains-toolbox installation

---

just-install-v4.json

It's only available on the store now. If somebody cares about that app, they should ask them to provide the packages on GitHub.

Remove bitpay

---

just-install-v4.json

Not under development since 2017. Not downloadable.

Remove mpc-hc

---

just-install-v4.json

Now they have one installer for all arch.

Change moonlight-qt download url
